name: main

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Pull sphinx image
        run: |
          docker pull ghcr.io/ldalek/docker-sphinx-latex

      - name: Build PDF document
        run: |
          make pdf

      - name: Deploy PDF document (artifact)
        uses: actions/upload-artifact@v6
        with:
          name: memfootprint.pdf
          path: latex/memfootprint.pdf
